# Generated by Django 3.0 on 2021-04-06 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pullrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='base_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='head_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='pullrequest',
            name='status',
            field=models.CharField(default='open', max_length=128),
        ),
    ]
